import { ContactType } from "../src/util/types";

export const contacts: ContactType[] = [
  {
    id: "jb6bezu",
    createdAt: 1712448222911,
    avatar: "https://picsum.photos/id/83/200/200",
    first: "Arlo",
    last: "Collins",
    twitter: "https://honorable-machinery.org/",
    notes: "",
    favorite: false,
  },
  {
    id: "tmfta2f",
    createdAt: 1712433063304,
    avatar: "https://picsum.photos/id/84/200/200",
    first: "Stuart",
    last: "Dietrich",
    twitter: "https://responsible-cell.net/",
    notes: "",
    favorite: false,
  },
  {
    id: "verp7yw",
    createdAt: 1712284657950,
    avatar: "https://picsum.photos/id/21/200/200",
    first: "Ivy",
    last: "Faheys",
    twitter: "https://our-mole.org/",
    notes: "",
    favorite: false,
  },
  {
    id: "fneyyep",
    createdAt: 1712447920130,
    avatar: "https://picsum.photos/id/35/200/200",
    first: "Milo",
    last: "Hagene",
    twitter: "https://rare-wraparound.org/",
    notes: "",
    favorite: false,
  },
  {
    id: "ivtdycc",
    createdAt: 1712336035965,
    avatar: "https://picsum.photos/id/23/200/200",
    first: "Maeve",
    last: "Keeling",
    twitter: "https://reasonable-latency.name/",
    notes: "",
    favorite: false,
  },
  {
    id: "tjhmw2g",
    createdAt: 1712283353767,
    avatar: "https://picsum.photos/id/41/200/200",
    first: "Demarcus",
    last: "Kub",
    twitter: "https://black-and-white-monster.com/",
    notes: "",
    favorite: true,
  },
  {
    id: "kt1pa1k",
    createdAt: 1712447747971,
    avatar: "https://picsum.photos/id/79/200/200",
    first: "Kaitlyn",
    last: "Leuschke",
    twitter: "https://elated-announcement.com/",
    notes: "",
    favorite: false,
  },
  {
    id: "z3te9nl",
    createdAt: 1712447209134,
    avatar: "https://picsum.photos/id/30/200/200",
    first: "Lorenzo",
    last: "Lowe",
    twitter: "https://villainous-anterior.info/",
    notes: "",
    favorite: false,
  },
  {
    id: "5kdlev3",
    createdAt: 1712283279221,
    avatar: "https://picsum.photos/id/48/200/200",
    first: "Abdullah",
    last: "Veum-O'Conners",
    twitter: "https://anchored-hood.net/",
    notes: "",
    favorite: false,
  },
  {
    id: "5jpv6le",
    createdAt: 1712285106502,
    avatar: "https://picsum.photos/id/54/200/200",
    first: "Reggie",
    last: "Veums",
    twitter: "https://favorable-mandate.info/",
    notes: "",
    favorite: true,
  },
  {
    id: "vc9pp09",
    createdAt: 1712283491495,
    avatar: "https://picsum.photos/id/52/200/200",
    first: "Margaret",
    last: "Zboncakz",
    twitter: "https://concrete-triangle.biz/",
    notes: "this person sucks",
    favorite: false,
  },
];
